name: auto publish

on:
  push:
    branches: 
      - master

jobs:
  publish-to-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch code
        uses: actions/checkout@v2
    
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: https://registry.npmjs.org/ 
      
      - uses: actions/cache@v2
        with:
            path: '**/node_modules'
            key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
            
      - name: install packages
        run: yarn add husky    
          
      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}